export interface IllustratorGenerateRequest {
  /**
   * Accompanying text prompt that will decide the style or theme of the code.
   */
  prompt: string;

  /**
   * Conditioning scale for qr controlnet
   */
  guidance_scale?: number;

  /**
   * Steps to run denoising
   */

  num_inference_steps?: number;
}

export interface IllustratorGenerateResponse {
  /**
   * URL of the QR code images that was generated by the model.
   */
  image_url: string;

  /**
   * Response latency in milliseconds.
   */
  model_latency_ms: number;

  /**
   * Unique ID of the QR code.
   * This ID can be used to retrieve the QR code image from the API.
   */
  id: string;
}
